### ISSUE TITLE
LOGROTATE_INTERVAL=hourly rotates on a daily basis

### ISSUE THREAD

**Issue by IrimieBogdan** [blacklabelops/logrotate#18]
I have the fallowing docker compose that is launched within a docker swarm. The rotation interval is set to hourly, but the logs are rotated daily.

```
version: '3.3'

services:
  log-roate:
    image: blacklabelops/logrotate
    environment:
      - LOGS_DIRECTORIES=/var/lib/docker/containers
      - LOGROTATE_COPIES=100
      - LOGROTATE_COMPRESSION=compress
      - LOGROTATE_INTERVAL=hourly
      - LOGROTATE_DATEFORMAT=-%Y-%m-%d-%s
    volumes:
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
    deploy:
      mode: global
```
