### ISSUE TITLE
Compression doesn't seem to work using docker-compose

### ISSUE THREAD

**Issue by janhollez** [blacklabelops/logrotate#29]
I'm using this in my docker-compose.yml:

```
 logrotate:                                                                                                                                                        
    image: "blacklabelops/logrotate"                                                                                                                                
    volumes:                                                                                                                                                        
      - /var/lib/docker/containers:/var/lib/docker/containers                                                                                                       
    environment:                                                                                                                                                    
      - LOGS_DIRECTORIES=/var/lib/docker/containers                                                                                                                 
      - LOGROTATE_INTERVAL=hourly                                                                                                                                   
      - LOGROTATE_COPIES=7                                                                                                                                          
      - LOGROTATE_SIZE=10M                                                                                                                                          
      - LOGROTATE_COMPRESSION=compress    
```

I don't see any compression when it rotates.
The logs were also much bigger when I first ran it and it didn't split it up in files of max 10M size, it just moved the old file to .1
