### ISSUE TITLE
I got an error no such files or directories

### ISSUE THREAD

**Issue by heangratha** [blacklabelops/logrotate#36]
executing: /bin/bash -c /usr/bin/logrotate.d/update-logrotate.sh; /usr/sbin/logrotate  --state=/logrotate-status/logrotate.status /usr/bin/logrotate.d/logrotate.conf 
find: "/var/log/docker: No such file or directory
find: /var/log/nginx": No such file or directory
```
├── docker-compose.yml
└── logs
    ├── file.log
    └── nginx
        ├── access.log
        └── error.log
```

This is my docker-compose.yaml setup

```
---
version: '2.4'
services:
  ssl:
    image: nginx:latest
    ports:
      - 2020:80
    volumes:
      - ./logs/nginx:/var/log/nginx
  logrotate:
    image: blacklabelops/logrotate:1.3
    environment:
      - LOGS_DIRECTORIES="/var/log/docker /var/log/nginx"
      - LOGROTATE_INTERVAL=hourly
      - LOGROTATE_COMPRESSION=compress
      - LOGROTATE_COPIES=30
      - TZ=Asia/Singapore
      - LOGROTATE_CRONSCHEDULE=* * * * * *
    volumes:
      - ./logs:/var/log/docker
      - ./logs/nginx:/var/log/nginx
```
