### ISSUE TITLE
[Invalid] LOGROTATE_INTERVAL in v1.3

### ISSUE THREAD

**Issue by HMWCS** [blacklabelops/logrotate#49]
<strong>Update:</strong> This issue was caused by my incorrect testing method (manually changing system clock). When letting time progress naturally, log rotation works correctly. Closing as invalid. v1.3 works as expected., Sorry for the confusion!

If possible, please feel free to delete this issue since it is invalid. Thank you!

<hr>
<del>
I'm using blacklabelops/logrotate:1.3 on macOS 15 Sequoia and noticed that when I set LOGROTATE_INTERVAL=daily, my logs don't actually rotate. The container shows it's setting up cron with @daily schedule, but nothing happens at midnight.

Looking at issue #18, this was supposedly fixed in v1.2 but seems to be broken again in 1.3.

I had to manually add LOGROTATE_CRONSCHEDULE="0 0 * * *" to get it working:

```
logrotate:
  image: blacklabelops/logrotate:1.3
  environment:
    - LOGS_DIRECTORIES=/var/log/nginx/access /var/log/nginx/error /var/log/certbot
    - LOGROTATE_INTERVAL=daily
    - LOGROTATE_CRONSCHEDULE=0 0 * * *  # Had to add this to make it work
```

Without the explicit cron schedule, logs just sit there and don't rotate. Could this be fixed again? Thanks!

**Comment by HMWCS** [comment]
Just to add, I'm seeing the same issue on Windows 11 (Docker Engine v28.1.1).

When using LOGROTATE_INTERVAL=daily on blacklabelops/logrotate:1.3, the container sets up the cron, but the daily schedule (0 0 * * *) never triggers at midnight.
```
  logrotate:
    image: blacklabelops/logrotate:1.3
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./log/certbot/renew:/var/log/certbot
    environment:
      - LOGS_DIRECTORIES=/var/log/nginx/access /var/log/nginx/error /var/log/certbot
      - LOGROTATE_INTERVAL=daily
      - LOGROTATE_CRONSCHEDULE=0 0 * * * *
      - LOGROTATE_PARAMETERS=vf
      - LOGROTATE_COPIES=7
      - LOGROTATE_DATEFORMAT=-%Y-%m-%d
      - LOG_FILE=/var/log/cron_debug/logrotate_cron_activity.log
    depends_on:
      - nginx
      - certbot
```


However, * * * * * * (every second) and 0 * * * * * (every minute) work fine without issues.
